:Author: gunnski
:Email: gunnarblom24497@gmail.com
:Date: 2024-04-25
:Revision: 1
:License: Public Domain

= Project: Remote-Solar-Irrigation-Pump


== Description:

Thin is the location of the code development for the Offgrid Solar Irrigation Capstone Project originally by WSU-V students, Emily, Nate, and Gunnar sponsored by TSMC Washington (formerly WaferTech). The project is at rest until further interest is found within the community. 

== Project Resources:
1. Google Drive - contains all original design and construction documents generated by the team since project start in October, 2023 (~6 months worth). 

https://drive.google.com/drive/folders/1OC2LOvfvoRQMiLNDkcjEEgQd0ed32whu

2. Onshape - Original design of the skid, part models, and a basic rain water collection idea. 

https://cad.onshape.com/documents/2a26568aabda4f27cc459c94/w/9f47c9ae6de155bdd2cd9205/e/d863c7d1090a392398fba123

== Other Resources:
1. WireViz - an opensource Wire Connector/Harnes diagram generator hosted on GitHub

https://github.com/wireviz/WireViz/tree/master



== License:
Solar-Irrigation-Pump © 2024 by Gunnar Blomquist, Emily Hickle, Nate Monti, Hannah Montgomery, Sally Hurst, & Jermey Cram is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International. To view a copy of this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
